services:
    ifile:
        container_name: ifile
        ports:
            - 3030:3030
        volumes:
            - ~/ifile/conf:/ifile/conf
            - ~/ifile/files:/ifile/files
            - ~/ifile/data:/ifile/data
            - ~/ifile/assets:/ifile/assets
            - ~/ifile/tmp:/ifile/tmp
            - ~/ifile/thumb:/ifile/thumb
            - ~/ifile/logs:/ifile/logs
            - ~/ifile/library:/ifile/library
        image:  docker.hlmirror.com/lgs821/ifile
