application:
  subdomain: ifilespace
  background_task: true
  multi_instance: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://ifile:3030/
services:
  ifile:
    # upstream: lgs821/ifile:2.5.9
    image: lgs821/ifile:2.5.9
    binds:
      - /lzcapp/var/conf:/ifile/conf
      - /lzcapp/var/files:/ifile/files
      - /lzcapp/var/data:/ifile/data
      - /lzcapp/var/assets:/ifile/assets
      - /lzcapp/var/tmp:/ifile/tmp
      - /lzcapp/var/thumb:/ifile/thumb
      - /lzcapp/var/logs:/ifile/logs
      - /lzcapp/var/library:/ifile/library
